version: "3.5"
services:
    web:
       image: nginx:latest
       container_name: my_nginx
       ports: 
         - "8080:80"

       networks:
         - app_network

       depends_on:
         - db    

    db: 
       image: postgres:latest
       container_name: database
       environment:
         POSTGRES_USER: MOHAMED
         POSTGRES_PASSWORD: PASSWORD
         POSTGRES_DB: MU_DB
       networks:
         - app_network         

       volumes:
         - appdata_volume:/var/lib/postgresql/data

networks:
    app_network:

volumes:  
    appdata_volume:
